/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu_Utama;
import form_cetak.Button_pemeriksaan;
import MASTER.Tambah_Admin;
import MASTER.A_Pasien;
import MASTER.B_DataDokter;
import MASTER.C_Obat;
import MASTER.D_Ruangan;
import MASTER.E_Pemeriksaan;
import MASTER.F_RawatInap;
import MASTER.F_RawatJalan;
import MASTER.G_Perawat;
import form_cetak.Button_rawatinap;
import form_cetak.Button_rawatjalan;
import form_pengaturan.Ubah_Password;
import static form_pengaturan.Ubah_Password.temp_username;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author DEFANI AHMAD RAMADHAN/180101054
 */
public class Menu_Utama extends javax.swing.JFrame {
    private A_Login Form_1_Login;
    public static String public_status="", public_nama="", public_admin="";
    
    /**
     * Creates new form Form_2_Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
        hak_akses();
        ImageIcon ico = new ImageIcon("src/gambar/icon2_original.png");
        setIconImage(ico.getImage());
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        data_pasien = new javax.swing.JMenuItem();
        data_dokter = new javax.swing.JMenuItem();
        data_obat = new javax.swing.JMenuItem();
        perawat = new javax.swing.JMenuItem();
        data_ruangan = new javax.swing.JMenuItem();
        pemeriksaan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rawat_jalan = new javax.swing.JMenuItem();
        rawat_inap = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        laporan_pasien = new javax.swing.JMenuItem();
        laporan_dokter = new javax.swing.JMenuItem();
        laporan_Obat = new javax.swing.JMenuItem();
        laporan_ruangan = new javax.swing.JMenuItem();
        laporan_perawat = new javax.swing.JMenuItem();
        laporan_pemeriksaan = new javax.swing.JMenuItem();
        rawatjalan = new javax.swing.JMenuItem();
        rawatinap = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ubah_password = new javax.swing.JMenuItem();
        tambah_admin = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU UTAMA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEM INFORMASI RUMAH SAKIT POS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 940, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon2_Utama.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UDB-BY_DFN.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 80, 80));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("DEFANI AHMAD RAMADHAN / 180101054");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form_2_Menu_Utama.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Master");

        data_pasien.setText("Pasien");
        data_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pasienActionPerformed(evt);
            }
        });
        jMenu1.add(data_pasien);

        data_dokter.setText("Dokter");
        data_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_dokterActionPerformed(evt);
            }
        });
        jMenu1.add(data_dokter);

        data_obat.setText("Obat");
        data_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_obatActionPerformed(evt);
            }
        });
        jMenu1.add(data_obat);

        perawat.setText("Perawat");
        perawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perawatActionPerformed(evt);
            }
        });
        jMenu1.add(perawat);

        data_ruangan.setText("Ruangan");
        data_ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_ruanganActionPerformed(evt);
            }
        });
        jMenu1.add(data_ruangan);

        pemeriksaan.setText("Pemeriksaan");
        pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemeriksaanActionPerformed(evt);
            }
        });
        jMenu1.add(pemeriksaan);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaksi");

        rawat_jalan.setText("Rawat Jalan");
        rawat_jalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawat_jalanActionPerformed(evt);
            }
        });
        jMenu3.add(rawat_jalan);

        rawat_inap.setText("Rawat Inap");
        rawat_inap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawat_inapActionPerformed(evt);
            }
        });
        jMenu3.add(rawat_inap);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Laporan");

        laporan_pasien.setText("Laporan Data Pasien");
        laporan_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pasienActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_pasien);

        laporan_dokter.setText("Laporan Data Dokter");
        laporan_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_dokterActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_dokter);

        laporan_Obat.setText("Laporan Data Obat");
        laporan_Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_ObatActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_Obat);

        laporan_ruangan.setText("Laporan Data Ruangan");
        laporan_ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_ruanganActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_ruangan);

        laporan_perawat.setText("Laporan Data Perawat");
        laporan_perawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_perawatActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_perawat);

        laporan_pemeriksaan.setText("Laporan Hasil Pemeriksaan");
        laporan_pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pemeriksaanActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_pemeriksaan);

        rawatjalan.setText("Nota Rawat Jalan");
        rawatjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatjalanActionPerformed(evt);
            }
        });
        jMenu7.add(rawatjalan);

        rawatinap.setText("Nota Rawat Inap");
        rawatinap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatinapActionPerformed(evt);
            }
        });
        jMenu7.add(rawatinap);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Pengaturan");

        ubah_password.setText("Ubah Password");
        ubah_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_passwordActionPerformed(evt);
            }
        });
        jMenu4.add(ubah_password);

        tambah_admin.setText("Tambah Admin");
        tambah_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_adminActionPerformed(evt);
            }
        });
        jMenu4.add(tambah_admin);

        jMenuBar1.add(jMenu4);

        keluar.setText("Log Out");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Form_1_Login = new A_Login();
        Form_1_Login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void data_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pasienActionPerformed
        A_Pasien frameform = new A_Pasien(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_pasienActionPerformed

    private void data_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_dokterActionPerformed
        B_DataDokter frameform = new B_DataDokter(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_dokterActionPerformed

    private void rawat_jalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawat_jalanActionPerformed
        F_RawatJalan frameform = new F_RawatJalan(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_rawat_jalanActionPerformed

    private void rawat_inapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawat_inapActionPerformed
        F_RawatInap frameform = new F_RawatInap(this, false);
        frameform.setVisible(true);
        
    }//GEN-LAST:event_rawat_inapActionPerformed

    private void laporan_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pasienActionPerformed
        try {
            String NamaFile = "src/laporan/report_pasien.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_pasienActionPerformed

    private void laporan_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_dokterActionPerformed
        try {
            String NamaFile = "src/laporan/report_datadokter.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_dokterActionPerformed

    private void laporan_ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_ObatActionPerformed
        try {
            String NamaFile = "src/laporan/report_dataobat.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_ObatActionPerformed

    private void laporan_ruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_ruanganActionPerformed
        try {
            String NamaFile = "src/laporan/report_ruangan.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_ruanganActionPerformed

    private void ubah_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_passwordActionPerformed
        Ubah_Password frameform = new Ubah_Password(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_ubah_passwordActionPerformed

    private void tambah_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_adminActionPerformed
        // TODO add your handling code here:
        Tambah_Admin frameform = new Tambah_Admin(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_tambah_adminActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
       // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_keluarMouseClicked

    private void data_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_obatActionPerformed
        // TODO add your handling code here:
        C_Obat frameform = new C_Obat(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_obatActionPerformed

    private void data_ruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_ruanganActionPerformed
        // TODO add your handling code here:
        D_Ruangan frameform = new D_Ruangan(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_ruanganActionPerformed

    private void pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemeriksaanActionPerformed
        // TODO add your handling code here:
        E_Pemeriksaan frameform = new E_Pemeriksaan(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_pemeriksaanActionPerformed

    private void perawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perawatActionPerformed
         // TODO add your handling code here:
         G_Perawat frameform = new G_Perawat(this, false);
        frameform.setVisible(true);
         
    }//GEN-LAST:event_perawatActionPerformed

    private void laporan_perawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_perawatActionPerformed
        // TODO add your handling code here:
        try {
            String NamaFile = "src/laporan/report_perawat.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_perawatActionPerformed

    private void laporan_pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pemeriksaanActionPerformed
        // TODO add your handling code here:
        Button_pemeriksaan frameform = new Button_pemeriksaan(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_laporan_pemeriksaanActionPerformed

    private void rawatjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatjalanActionPerformed
        // TODO add your handling code here:
        Button_rawatjalan frameform = new Button_rawatjalan(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_rawatjalanActionPerformed

    private void rawatinapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatinapActionPerformed
        // TODO add your handling code here:
        Button_rawatinap frameform = new Button_rawatinap(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_rawatinapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem data_dokter;
    private javax.swing.JMenuItem data_obat;
    private javax.swing.JMenuItem data_pasien;
    private javax.swing.JMenuItem data_ruangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenuItem laporan_Obat;
    private javax.swing.JMenuItem laporan_dokter;
    private javax.swing.JMenuItem laporan_pasien;
    private javax.swing.JMenuItem laporan_pemeriksaan;
    private javax.swing.JMenuItem laporan_perawat;
    private javax.swing.JMenuItem laporan_ruangan;
    private javax.swing.JMenuItem pemeriksaan;
    private javax.swing.JMenuItem perawat;
    private javax.swing.JMenuItem rawat_inap;
    private javax.swing.JMenuItem rawat_jalan;
    private javax.swing.JMenuItem rawatinap;
    private javax.swing.JMenuItem rawatjalan;
    private javax.swing.JMenuItem tambah_admin;
    private javax.swing.JMenuItem ubah_password;
    // End of variables declaration//GEN-END:variables

    private void hak_akses() {
        ActionListener taskPerformer = new ActionListener() {

        public void actionPerformed(ActionEvent evt) {            
            if(public_status.equals("Admin")){
                
            }else
            if(public_status.equals("Admin")){
                
            }
        }        
        };
        new Timer(1000, taskPerformer).start();
    }
}
