/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MASTER;

import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author DEFANI AHMAD RAMADHAN / 180101054
 */
public class B_DataDokter extends javax.swing.JDialog {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    public Statement stt;
    public Connection con;
    private TableColumn column;
    String temp_kd_dokter="";

    /**
     
     */
    public B_DataDokter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"Kode Dokter","Nama Dokter","No Telepon","Jenis Kelamin","Alamat","Spesialis","Biaya"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        tampil();
        aturKolom();
        aturFokus();
        hitungData();
        ImageIcon ico = new ImageIcon("src/gambar/icon2_original.png");
        setIconImage(ico.getImage());
    }

    B_DataDokter() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        e_spesialis = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        e_biaya = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        e_kd_dokter = new javax.swing.JTextField();
        e_namadokter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pencarian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        e_jeniskelamin = new javax.swing.JComboBox();
        jumlah_data = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        e_alamat = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        e_telepon = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA DOKTER");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_spesialis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "KANDUNGAN", "ANAK", "GIGI", "JANTUNG", "MATA", "PENYAKIT DALAM", "TULANG", "GIZI", "THT" }));
        e_spesialis.setEnabled(false);
        getContentPane().add(e_spesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 250, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Spesialis");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        e_biaya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_biaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_biaya.setMargin(new java.awt.Insets(0, 3, 0, 3));
        e_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_biayaActionPerformed(evt);
            }
        });
        e_biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_biayaKeyTyped(evt);
            }
        });
        getContentPane().add(e_biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 250, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Biaya");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Alamat");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 12, 70, 64));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama Dokter");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 142, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 177, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 142, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 104, -1, -1));

        e_kd_dokter.setEditable(false);
        e_kd_dokter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_kd_dokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_kd_dokter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        e_kd_dokter.setMargin(new java.awt.Insets(0, 3, 0, 3));
        e_kd_dokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_kd_dokterKeyTyped(evt);
            }
        });
        getContentPane().add(e_kd_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 98, 96, 30));

        e_namadokter.setEditable(false);
        e_namadokter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_namadokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_namadokter.setMargin(new java.awt.Insets(0, 3, 0, 3));
        e_namadokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_namadokterKeyTyped(evt);
            }
        });
        getContentPane().add(e_namadokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 134, 250, 30));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setRowHeight(17);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 770, 160));

        cari.setText("Cari");
        cari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 284, 87, 37));

        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tambah.setBorderPainted(false);
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.setIconTextGap(2);
        tambah.setMargin(new java.awt.Insets(2, 0, 2, 0));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 87, 37));

        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.setEnabled(false);
        simpan.setIconTextGap(1);
        simpan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 286, 87, 37));

        ubah.setText("Ubah");
        ubah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.setEnabled(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 286, 87, 37));

        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.setEnabled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 286, 87, 37));

        refresh.setText("BERSIHKAN");
        refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.setMargin(new java.awt.Insets(2, 0, 2, 0));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 87, 37));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah Data");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 533, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA DOKTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 50));

        pencarian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pencarian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        pencarian.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pencarian.setMargin(new java.awt.Insets(0, 3, 0, 3));
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });
        getContentPane().add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 284, 232, 37));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kode Dokter");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 533, -1, -1));

        e_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Laki-Laki", "Perempuan" }));
        e_jeniskelamin.setEnabled(false);
        getContentPane().add(e_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, 30));

        jumlah_data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah_data.setForeground(new java.awt.Color(255, 255, 255));
        jumlah_data.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jumlah_data.setText("0000");
        getContentPane().add(jumlah_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 533, 38, -1));

        batal.setText("Batal");
        batal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batal.setMargin(new java.awt.Insets(2, 0, 2, 0));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 286, 87, 37));

        e_alamat.setEditable(false);
        e_alamat.setColumns(20);
        e_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_alamat.setRows(5);
        e_alamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_alamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(e_alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 250, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Jenis Kelamin");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 213, -1, -1));

        e_telepon.setEditable(false);
        e_telepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_telepon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_telepon.setMargin(new java.awt.Insets(0, 3, 0, 3));
        e_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_teleponActionPerformed(evt);
            }
        });
        e_telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_teleponKeyTyped(evt);
            }
        });
        getContentPane().add(e_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 170, 250, 30));

        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 523, 87, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Master.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        e_kd_dokter.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        e_namadokter.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        e_telepon.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        e_jeniskelamin.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        e_alamat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        e_spesialis.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        e_biaya.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        
        temp_kd_dokter = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        enable_field();
        tambah.setEnabled(false);
        hapus.setEnabled(true);
        ubah.setEnabled(true);
        simpan.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        empty_field();
        enable_field();
        penomoran_otomatis();
        fungsi_simpan=true;
        fungsi_ubah=false;
        tambah.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(true);
        e_kd_dokter.requestFocus();                
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        //Simpan Data
        if(fungsi_simpan==true && fungsi_ubah==false){
            if(e_kd_dokter.getText().isEmpty() || e_namadokter.getText().isEmpty() || e_telepon.getText().isEmpty() ||e_jeniskelamin.getSelectedItem().equals("-")){
                JOptionPane.showMessageDialog(this, "Lengkapi Data Terlebih Dahulu !");
            }else{
                cek_double_data_simpan();
            }
        }
        //Ubah Data
        else if(fungsi_simpan==false && fungsi_ubah==true){
            if(e_kd_dokter.getText().isEmpty() || e_namadokter.getText().isEmpty() || e_telepon.getText().isEmpty() ||e_jeniskelamin.getSelectedItem().equals("-")){
                JOptionPane.showMessageDialog(this, "Lengkapi Data Terlebih Dahulu !");
            }else{
                cek_double_data_ubah();
            }
        }
        hitungData();
        pencarian.requestFocus();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        if(e_kd_dokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        } else{
            enable_field();
            ubah.setEnabled(false);
            tambah.setEnabled(false);
            hapus.setEnabled(false);
            simpan.setEnabled(true);
            fungsi_simpan=false;
            fungsi_ubah=true;
        }
        e_kd_dokter.requestFocus();
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if(e_kd_dokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Pasien ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM dokter where kd_dokter='"+e_kd_dokter.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampil();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }
                empty_field();
            }
        }
        batalActionPerformed(evt);
    }//GEN-LAST:event_hapusActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tampil();
        if(fungsi_simpan==true && fungsi_ubah==false){
            empty_field();
        }else
        if(fungsi_ubah==true && fungsi_simpan==false){

        }else{
            empty_field();
        }
        disable_field();
        tambah.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        fungsi_simpan=false;
        fungsi_ubah=false;
        hitungData();
        pencarian.requestFocus();
    }//GEN-LAST:event_refreshActionPerformed

    private void e_namadokterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_namadokterKeyTyped
        FilterHanyaHuruf(evt);
        String batas = e_namadokter.getText();
        if(batas.length()>=150){
            evt.consume();
        }
    }//GEN-LAST:event_e_namadokterKeyTyped

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        fungsi_pencarian();
        hitungData();
        pencarian.requestFocus();
    }//GEN-LAST:event_cariActionPerformed

    private void e_kd_dokterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_kd_dokterKeyTyped
        FilterHanyaAngka(evt);
        String batas = e_kd_dokter.getText();
        if(batas.length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_e_kd_dokterKeyTyped

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        fungsi_pencarian();
        hitungData();
    }//GEN-LAST:event_pencarianActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        tampil();
        if(fungsi_simpan==true && fungsi_ubah==false){
            empty_field();
        }else
        if(fungsi_ubah==true && fungsi_simpan==false){

        }else{
            empty_field();
        }
        disable_field();
        tambah.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        fungsi_simpan=false;
        fungsi_ubah=false;
        pencarian.requestFocus();
    }//GEN-LAST:event_batalActionPerformed

    private void e_teleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_teleponKeyTyped
        
    }//GEN-LAST:event_e_teleponKeyTyped

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void e_alamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_alamatKeyTyped
        String batas = e_alamat.getText();
        if(batas.length()>=250){
            evt.consume();
        }
    }//GEN-LAST:event_e_alamatKeyTyped

    private void e_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_teleponActionPerformed

    private void e_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_biayaActionPerformed

    private void e_biayaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_biayaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_e_biayaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_DataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_DataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_DataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_DataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                B_DataDokter dialog = new B_DataDokter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JTextArea e_alamat;
    private javax.swing.JTextField e_biaya;
    private javax.swing.JComboBox e_jeniskelamin;
    private javax.swing.JTextField e_kd_dokter;
    private javax.swing.JTextField e_namadokter;
    private javax.swing.JComboBox e_spesialis;
    private javax.swing.JTextField e_telepon;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah_data;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton refresh;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
    
    private void empty_field() {
        e_kd_dokter.setText(null);
        e_namadokter.setText(null);
        e_telepon.setText(null);
        e_alamat.setText(null);
        e_jeniskelamin.setSelectedItem("-");
        e_spesialis.setSelectedItem("-");
        e_biaya.setText(null);
         pencarian.setText(null);
    }

    private void enable_field() {
        e_kd_dokter.setEditable(true);
        e_namadokter.setEditable(true);
        e_telepon.setEditable(true);
        e_jeniskelamin.setEnabled(true);
        e_alamat.setEditable(true);
        e_spesialis.setEnabled(true);
        e_biaya.setEnabled(true);
    }
    
    private void disable_field() {
        e_kd_dokter.setEditable(false);
        e_namadokter.setEditable(false);
        e_telepon.setEditable(false);
        e_jeniskelamin.setEnabled(false);
        e_alamat.setEditable(false);
        e_spesialis.setEnabled(false);
        e_biaya.setEnabled(false);
    }
    
    private void FilterHanyaHuruf(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (! ((Character.isLetter(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_COMMA) || (c == KeyEvent.VK_SPACE) || (c == KeyEvent.VK_PERIOD) )))
        {
            evt.consume();            
        }
    }
    
    private void FilterHanyaAngka(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))))
        {
            evt.consume();            
        }
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    private void cek_double_data_simpan() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("select * from dokter where kd_dokter = '"+e_kd_dokter.getText()+"'");
            if (re.next()){
                JOptionPane.showMessageDialog(null, "Kode Dokter : "+e_kd_dokter.getText()+"\nSudah Terdaftar\nSilahkan Ganti Kode Dokter !", "Error", JOptionPane.WARNING_MESSAGE);
            }else{
                fungsi_simpan_data();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Salah Prosedur (Cek Double Data) Simpan!");
        }
    }
    
    private void cek_double_data_ubah() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("select * from dokter where kd_dokter != '"+temp_kd_dokter+"' AND kd_dokter='"+e_kd_dokter.getText()+"'");
            if (re.next()){
                JOptionPane.showMessageDialog(this, "Kode Dokter : "+e_kd_dokter.getText()+"\nSudah Terdaftar\nSilahkan Ganti Kode Dokter!", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else{
                fungsi_ubah_data();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Salah Prosedur (Cek Double Data) Ubah!");
        }
    }
    
    private void fungsi_simpan_data() {
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            koneksi.createStatement().executeUpdate("INSERT INTO dokter VALUES('"+e_kd_dokter.getText()+"'"
            + ",'"+e_namadokter.getText()+"','"+e_telepon.getText()+"','"+e_jeniskelamin.getSelectedItem()+"'"
            + ",'"+e_alamat.getText()+"','"+e_spesialis.getSelectedItem()+"','"+e_biaya.getText()+"')");
            JOptionPane.showMessageDialog(this, "Data Disimpan !");            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data Gagal Disimpan !");
        }
        tambah.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        fungsi_simpan=false;
        fungsi_ubah=false;
        disable_field();
        tampil();
    }
    
    private void fungsi_ubah_data() {
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            koneksi.createStatement().executeUpdate("UPDATE dokter SET kd_dokter='"+e_kd_dokter.getText()+"'"
            + ",nama_dokter='"+e_namadokter.getText()+"',no_telp='"+e_telepon.getText()+"'"
            + ",jenis_kelamin='"+e_jeniskelamin.getSelectedItem()+"'"
            + ",alamat='"+e_alamat.getText()+"',spesialis='"+e_spesialis.getSelectedItem()+"',harga='"+e_biaya.getText()+"'"
            + " WHERE kd_dokter='"+temp_kd_dokter+"'");
           JOptionPane.showMessageDialog(this, "Data Diubah !");
        } catch (SQLException ex1) {
           JOptionPane.showMessageDialog(this, "Data Gagal Diubah !");
        }
        tambah.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        fungsi_simpan=false;
        fungsi_ubah=false;
        disable_field();
        tampil();
    }
    
    private void tampil() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM dokter ORDER BY kd_dokter");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }   

    private void penomoran_otomatis() {
        int no_kode_dokter=0;
        String temp_kode_dokter="";
        try {
            koneksi();
            String sql = "select kd_dokter from dokter order by kd_dokter desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_kode_dokter = res.getString(1);                
                String nomor_blkg = temp_kode_dokter.substring(2,4);
                no_kode_dokter=Integer.parseInt(nomor_blkg);
            }
                        
            no_kode_dokter++;
            String nilai=String.valueOf(no_kode_dokter);                      
            if(nilai.length()==1){
                e_kd_dokter.setText("D00"+no_kode_dokter);
            }else
            if(nilai.length()==2){
                e_kd_dokter.setText("D0"+no_kode_dokter);
            }else
            if(nilai.length()==3){
                e_kd_dokter.setText("D"+no_kode_dokter);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(125);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(200); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(3);
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(4);
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(5);
        column.setPreferredWidth(200);
        column = jTable1.getColumnModel().getColumn(6);
        column.setPreferredWidth(200);
       
    }        

    private void fungsi_pencarian() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
                tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM dokter where kd_dokter LIKE '%"+pencarian.getText()+"%'"
            +"or nama_dokter like '%"+pencarian.getText()+"%'"
            +"or jenis_kelamin like '%"+pencarian.getText()+"%'"
            +"or alamat like '%" + pencarian.getText()+"%' ORDER BY kd_dokter");
            while(re.next()){                    
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5)};
                tabel.addRow(tabel_master);
            }
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan !");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Fungsi Pencarian !");
        }
    }

    private void aturFokus() {
        e_kd_dokter.setNextFocusableComponent(e_namadokter);
        e_namadokter.setNextFocusableComponent(e_telepon);
        e_telepon.setNextFocusableComponent(e_telepon);
        e_jeniskelamin.setNextFocusableComponent(e_alamat);
        e_alamat.setNextFocusableComponent(e_kd_dokter);
    }
    
    private void hitungData() {
        int total_baris = jTable1.getRowCount();
        if(String.valueOf(total_baris).length()==1){
            jumlah_data.setText("000"+total_baris);
        }else
        if(String.valueOf(total_baris).length()==2){
            jumlah_data.setText("00"+total_baris);
        }else
        if(String.valueOf(total_baris).length()==3){
            jumlah_data.setText("0"+total_baris);
        }else
        if(String.valueOf(total_baris).length()==4){
            jumlah_data.setText(""+total_baris);
        }
    }        
}
