/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MASTER;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import MASTER.C_Obat;
import MASTER.A_Pasien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author DEFANI AHMAD RAMADHAN / 180101054
 */
public class F_RawatJalan extends javax.swing.JDialog {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    private Connection Con;
    private Statement stm;
    public Statement stt;
    public java.sql.Connection con;
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
    private TableColumn column;
    String temp_kd_jalan="";
    
    /**

     */
    public F_RawatJalan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"KODE RAWAT JALAN","KODE DOKTER","NAMA DOKTER","SPESIALIS","BIAYA DOKTER","KODE PASIEN","NAMA PASIEN","KODE OBAT","NAMA OBAT","HARGA OBAT","TANGGAL PERIKSA"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        tampilkan_data();
        setLocationRelativeTo(this);
        aktif(false);
        setTombol(true);
        aturKolom();
        ImageIcon ico = new ImageIcon("src/gambar/icon2_original.png");
        setIconImage(ico.getImage());
        
    }

    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        e_spesialis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        e_biaya = new javax.swing.JTextField();
        e_harga = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        e_kdrawatjalan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        e_namapasien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        e_kdpasien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cari_pasien = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        e_namaobat = new javax.swing.JTextField();
        e_namadokter = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        e_kddokter = new javax.swing.JTextField();
        e_tanggalperiksa = new com.toedter.calendar.JDateChooser();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        cari_kdobat = new javax.swing.JButton();
        e_kdobat = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA RAWAT JALAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Spesialis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText(":");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        e_spesialis.setEditable(false);
        e_spesialis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_spesialis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_spesialis.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_spesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Biaya Dokter");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        e_biaya.setEditable(false);
        e_biaya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_biaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_biaya.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 220, 30));

        e_harga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_harga.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_harga.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 220, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText(":");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 10, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Harga Obat");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kode Dokter");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Dokter");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        cari.setText("Cari");
        cari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 87, 30));

        e_kdrawatjalan.setEditable(false);
        e_kdrawatjalan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_kdrawatjalan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_kdrawatjalan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        e_kdrawatjalan.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_kdrawatjalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, 30));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(17);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1021, 140));

        refresh.setText("BERSIHKAN");
        refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 87, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RAWAT JALAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        batal.setText("Batal");
        batal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batal.setMargin(new java.awt.Insets(2, 0, 2, 0));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 87, 37));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kode Rawat Jalan");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        e_namapasien.setEditable(false);
        e_namapasien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_namapasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_namapasien.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_namapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nama Pasien");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kode Pasien");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        e_kdpasien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_kdpasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_kdpasien.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_kdpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Kode Obat");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tanggal Periksa");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nama Obat");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        cari_pasien.setText("CARI");
        cari_pasien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cari_pasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari_pasien.setMargin(new java.awt.Insets(2, 0, 2, 0));
        cari_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_pasienActionPerformed(evt);
            }
        });
        getContentPane().add(cari_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, 30));

        pencarian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pencarian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        pencarian.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 220, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText(":");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 10, -1));

        e_namaobat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_namaobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_namaobat.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 220, 30));

        e_namadokter.setEditable(false);
        e_namadokter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_namadokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_namadokter.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_namadokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 220, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText(":");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 70, 64));

        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 87, 37));

        e_kddokter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_kddokter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_kddokter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        e_kddokter.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(e_kddokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 220, 30));

        e_tanggalperiksa.setDateFormatString("dd MMMM  yyyy");
        e_tanggalperiksa.setEnabled(false);
        getContentPane().add(e_tanggalperiksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 240, 30));

        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.setEnabled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 87, 37));

        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.setEnabled(false);
        simpan.setIconTextGap(1);
        simpan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 87, 37));

        cari_kdobat.setText("CARI");
        cari_kdobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cari_kdobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cari_kdobat.setMargin(new java.awt.Insets(2, 0, 2, 0));
        cari_kdobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_kdobatActionPerformed(evt);
            }
        });
        getContentPane().add(cari_kdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 80, 30));

        e_kdobat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        e_kdobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        e_kdobat.setMargin(new java.awt.Insets(0, 3, 0, 3));
        e_kdobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_kdobatActionPerformed(evt);
            }
        });
        getContentPane().add(e_kdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 130, 30));

        edit.setText("Update");
        edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.setEnabled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 87, 37));

        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tambah.setBorderPainted(false);
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.setIconTextGap(2);
        tambah.setMargin(new java.awt.Insets(2, 0, 2, 0));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 87, 37));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/POS_TAMBAHAN.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(140, 140));
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 160, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Master 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tampilkan_data();
        if(fungsi_simpan==true && fungsi_ubah==false){
            empty_field();
        }else
        if(fungsi_ubah==true && fungsi_simpan==false){

        }else{
            empty_field();
        }
        disable_field();
        tambah.setEnabled(true);
        edit.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        fungsi_simpan=false;
        fungsi_ubah=false;
        
    }//GEN-LAST:event_refreshActionPerformed

    private void empty_field() {
        e_kdrawatjalan.setText(null);
        e_kddokter.setText(null);
        e_namadokter.setText(null);
        e_biaya.setText(null);
        e_kdpasien.setText(null);
        e_namapasien.setText(null);
        e_kdobat.setText(null);
        e_tanggalperiksa.setDate(null);
        e_namaobat.setText(null);
        pencarian.setText(null);
    }

    private void enable_field() {
        e_kdrawatjalan.setEditable(true);
        e_kddokter.setEditable(true);
        e_kdpasien.setEditable(true);
    }
    
    private void disable_field() {
        e_kdrawatjalan.setEditable(false);
        e_kddokter.setEditable(false);
        e_kdpasien.setEditable(false);
    }
    
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void cari_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_pasienActionPerformed
        // TODO add your handling code here:
        String kode_pasien = e_kdpasien.getText();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/RumahSakit", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT i.kd_pasien, i.nama_pasien, i.kd_dokter, i.nama_dokter, a.spesialis, a.harga, i.hasil, i.tgl_pemeriksaan, a.harga FROM pemeriksaan AS i INNER JOIN dokter AS a ON i.kd_dokter = a.kd_dokter WHERE i.kd_pasien = '"+kode_pasien+"' && i.hasil = 'Rawat Jalan' ORDER BY i.kd_pasien ;";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{

e_namapasien.setText(rs.getString("nama_pasien"));
e_kddokter.setText(rs.getString("kd_dokter"));
e_namadokter.setText(rs.getString("nama_dokter"));
java.util.Date tgl_lhr=null;
        try{
            tgl_lhr = new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString("tgl_pemeriksaan"));            
        }catch(ParseException ex){
            System.out.println(ex);
        }
        e_tanggalperiksa.setDate(tgl_lhr);
e_spesialis.setText(rs.getString("spesialis"));
e_biaya.setText(rs.getString("harga"));


JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
}
else
{
JOptionPane.showMessageDialog(null, "Data tidak ditemukan Atau Data Tersebut Bukan Termasuk Rawat Jalan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
}
statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
                                         
    }//GEN-LAST:event_cari_pasienActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
e_kdrawatjalan.setText("");
e_kddokter.setText("");
e_biaya.setText("");
e_namadokter.setText("");
e_kdpasien.setText("");
e_namapasien.setText("");
e_kdobat.setText("");
e_harga.setText("");
e_namaobat.setText("");
aktif(false);
setTombol(true);        
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    if(e_kdrawatjalan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Pemeriksaan ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM rawat_jalan where kd_jalan='"+e_kdrawatjalan.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }
                
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

String user_id = e_kdrawatjalan.getText();
String kode_dokter = e_kddokter.getText();
String nama_dokter = e_namadokter.getText();
String sp = e_spesialis.getText();
String biaya_dokter = e_biaya.getText();
String kode_pasien = e_kdpasien.getText();
String nama_pasien = e_namapasien.getText();
String tanggal_periksa = String.valueOf(kal.format(e_tanggalperiksa.getDate()));;
String nama_obat = e_namaobat.getText();
String kode_obat = e_kdobat.getText();
String harga_obat = e_harga.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/RumahSakit", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="UPDATE rawat_jalan SET kd_dokter='"+kode_dokter+"',nama_dokter='"+nama_dokter+"',spesialis='"+sp+"',biaya_dokter='"+biaya_dokter+"',kd_pasien='"+kode_pasien+"',nama_pasien='"+nama_pasien+"',kd_resep='"+kode_obat+"',resep_obat='"+nama_obat+"',harga='"+harga_obat+"',tgl_periksa='"+tanggal_periksa+"' WHERE kd_jalan LIKE '"+user_id+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}finally{
tampilkan_data();
}
    }//GEN-LAST:event_editActionPerformed


    
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        //Simpan Data
                  String user_id = e_kdrawatjalan.getText();

String kode_dokter = e_kddokter.getText();
String nama_dokter = e_namadokter.getText();
String sp = e_spesialis.getText();
String biaya_dokter = e_biaya.getText();
String kode_pasien = e_kdpasien.getText();
String nama_pasien = e_namapasien.getText();
String kode_obat = e_kdobat.getText();
String tanggal_periksa = String.valueOf(kal.format(e_tanggalperiksa.getDate()));;
String nama_obat = e_namaobat.getText();
String harga_obat = e_harga.getText();
{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/RumahSakit", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into rawat_jalan values('"+user_id+"','"+kode_dokter+"','"+nama_dokter+"','"+sp+"','"+biaya_dokter+"','"+kode_pasien+"','"+nama_pasien+"','"+kode_obat+"','"+nama_obat+"','"+harga_obat+"','"+tanggal_periksa+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
aktif(true);
e_kdrawatjalan.setText("");

e_kddokter.setText("");
e_namadokter.setText("");
e_biaya.setText("");
e_kdpasien.setText("");
e_namapasien.setText("");
e_kdobat.setText("");
e_harga.setText("");
e_namaobat.setText("");

koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
finally {
tampilkan_data();
}
    }                 
    }//GEN-LAST:event_simpanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        aktif(true);
        setTombol(false);
        penomoran_otomatis();
    }//GEN-LAST:event_tambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        e_kdrawatjalan.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        e_kddokter.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        e_namadokter.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        e_spesialis.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        e_biaya.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        e_kdpasien.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        e_namapasien.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        e_kdobat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        e_namaobat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        e_harga.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        java.util.Date tgl_lhr=null;
        try{
            tgl_lhr = new SimpleDateFormat("yyyy-MM-dd").parse(tabel.getValueAt(jTable1.getSelectedRow(), 10).toString());            
        }catch(ParseException ex){
            System.out.println(ex);
        }
        e_tanggalperiksa.setDate(tgl_lhr);
        
        
        temp_kd_jalan = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        
        aktif(true);
        tambah.setEnabled(false);
        hapus.setEnabled(true);
        edit.setEnabled(true);
        simpan.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cari_kdobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_kdobatActionPerformed
        // TODO add your handling code here:
        String kode_obat = e_kdobat.getText();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/RumahSakit", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM obat WHERE kd_obat like '"+kode_obat+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
aktif(true);
setTombol(false);
e_namaobat.setText(rs.getString(2));
e_harga.setText(rs.getString(4));

JOptionPane.showMessageDialog(null, "Data ditemukan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
}
else
{
JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
}
statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }//GEN-LAST:event_cari_kdobatActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        fungsi_pencarian();
        pencarian.requestFocus();
    }//GEN-LAST:event_cariActionPerformed

    private void e_kdobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_kdobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_kdobatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_RawatJalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                F_RawatJalan dialog = new F_RawatJalan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
            }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton cari_kdobat;
    private javax.swing.JButton cari_pasien;
    private javax.swing.JTextField e_biaya;
    private javax.swing.JTextField e_harga;
    private javax.swing.JTextField e_kddokter;
    private javax.swing.JTextField e_kdobat;
    private javax.swing.JTextField e_kdpasien;
    private javax.swing.JTextField e_kdrawatjalan;
    private javax.swing.JTextField e_namadokter;
    private javax.swing.JTextField e_namaobat;
    private javax.swing.JTextField e_namapasien;
    private javax.swing.JTextField e_spesialis;
    private com.toedter.calendar.JDateChooser e_tanggalperiksa;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton refresh;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
    
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
  
         private void tampilkan_data() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM rawat_jalan ORDER BY kd_jalan");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7),re.getString(8),re.getString(9),re.getString(10),re.getString(11)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }

         private void penomoran_otomatis() {
        int no_kode_rawat_jalan=0;
        String temp_kode_rawat_jalan="";
        try {
            koneksi();
            String sql = "select kd_jalan from rawat_jalan order by kd_jalan desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_kode_rawat_jalan = res.getString(1);                
                String nomor_blkg = temp_kode_rawat_jalan.substring(3,5);
                no_kode_rawat_jalan=Integer.parseInt(nomor_blkg);
            }
                        
            no_kode_rawat_jalan++;
            String nilai=String.valueOf(no_kode_rawat_jalan);                      
            if(nilai.length()==1){
                e_kdrawatjalan.setText("RJ00"+no_kode_rawat_jalan);
            }else
            if(nilai.length()==2){
                e_kdrawatjalan.setText("RJ0"+no_kode_rawat_jalan);
            }else
            if(nilai.length()==3){
                e_kdrawatjalan.setText("RJ"+no_kode_rawat_jalan);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
         
    private void open_db() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection Con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/rumahsakit", "root", "");
            Statement stm = (Statement) Con.createStatement();

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi gagal");
            System.out.println(e.getMessage());
        }
    }

    private void aktif(boolean x) {
      
      e_kdpasien.setEditable(x);
      e_kdobat.setEditable(x);
      e_namapasien.setEditable(!x);
      e_kddokter.setEditable(!x);
      e_namaobat.setEditable(!x);
      e_kdrawatjalan.requestFocus();
      e_tanggalperiksa.setEnabled(false);}

    private void setTombol(boolean t) {
     tambah.setEnabled(t);
     
     simpan.setEnabled(!t);
     hapus.setEnabled(!t);
     edit.setEnabled(!t);
     batal.setEnabled(!t);
    }
    
    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(125);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(125); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(6); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(7); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(8); 
        column.setPreferredWidth(125);
        column = jTable1.getColumnModel().getColumn(9); 
        column.setPreferredWidth(125);
    } 
    
     private void fungsi_pencarian() {
         
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
                tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/rumahsakit","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM rawat_jalan where kd_jalan LIKE '%"+pencarian.getText()+"%'"
            +"or kd_pasien like '%"+pencarian.getText()+"%'"
            +"or nama_dokter like '%"+pencarian.getText()+"%'"
            +"or nama_pasien like '%" + pencarian.getText()+"%' ORDER BY kd_jalan");
            while(re.next()){                    
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7),re.getString(8),re.getString(9)};
                tabel.addRow(tabel_master);
            }
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan !");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Fungsi Pencarian !");
        }
    }
    
    
    
    
}


